fix the 15.7 bug
Error: file Firmware/.trustcache does not exist, or is a directory

this happens because the ramdisk doesn't get the ipsw url correctly, so this uses the code from palera1n to get the ipsw url correctly.